### PR TITLE
BLD: standards, enable pypi, simplify conda build

### LINKED ISSUE #3: Switch to GHA and update for tag 3.3.38
## Expected Behavior

Use gha instead of travis
Deploy a build that matches 3.3.38

## Current Behavior

travis
old build

## Possible Solution

Generate a new patch + redo the pipeline

## Context

Recent updates to the daq packages need to be deployed in controls

### LINKED ISSUE #4: Figure out how to do a pypi upload
This probably isn't too hard, but this repo is relying on conda recipe patching to make the conda build so some reworking will be needed to make the pypi build work.

### PR DESCRIPTION
**Pull request by ZLLentz**
## Description

- pyproject.toml/setuptools_scm
- extract the build script from conda patch files and instead run it standalone
- add pypi builds to the ci
- fix many ci and build issues

## Motivation and Context

It's annoying to have _any_ manual steps at all in the repo, much better to be able to tag and move on.
After this change, the only maintenance step needed to rebuild after a daq interface fix is to tag the repo with the new daq version. It will then upload to pypi and to pcds-tag.

closes #3 
closes #4 

## How Has This Been Tested?

Interactively and on my user account gha

## Where Has This Been Documented?

I've updated the readme

### CODE REVIEW

**Comment by ZLLentz** [comment]
I'm pushing this at the end of the day, might need some more work tomorrow

**Comment by ZLLentz** [comment]
I've fixed this to the best of my understanding.
I'm going to do a self-review, then request reviews from Robert and Ken, who are both on vacation.
I suspect neither will have time to review until Tuesday but this shouldn't be urgent.

**Comment by ZLLentz** [comment]
I personally think this looks good.
I'm sending review requests and I'll mention it on Tuesday.

**Comment by ZLLentz** [comment]
In retrospect, it may have been better to find a way to modify the ci-helpers to allow what this repo needs rather than copy/paste the workflow and add the additional steps required here

**Review by klauer — APPROVED** [review]
Looks good - and more importantly, seems to run successfully on GHA. 👍

**Comment by ZLLentz** [comment]
Ok, great. I'm going to merge this so I can try to get a new conda env ready with the latest daq interface changes included.

**Pull request merged**
